BEGIN;

--
-- Class Action as table action
--
CREATE TABLE "action" (
    "id" bigserial PRIMARY KEY,
    "userId" bigint NOT NULL,
    "captureId" bigint,
    "type" text NOT NULL,
    "title" text NOT NULL,
    "notes" text,
    "dueAt" timestamp without time zone,
    "reminderAt" timestamp without time zone,
    "isCompleted" boolean NOT NULL,
    "priority" text NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "completedAt" timestamp without time zone
);

-- Indexes
CREATE INDEX "action_user_idx" ON "action" USING btree ("userId");
CREATE INDEX "action_capture_idx" ON "action" USING btree ("captureId");
CREATE INDEX "action_due_idx" ON "action" USING btree ("dueAt");
CREATE INDEX "action_completed_idx" ON "action" USING btree ("isCompleted");
CREATE INDEX "action_reminder_idx" ON "action" USING btree ("reminderAt");

--
-- Class Capture as table capture
--
CREATE TABLE "capture" (
    "id" bigserial PRIMARY KEY,
    "userId" bigint NOT NULL,
    "type" text NOT NULL,
    "originalUrl" text,
    "thumbnailUrl" text,
    "quickDescription" text,
    "quickType" text,
    "extractedText" text,
    "aiSummary" text,
    "tags" text,
    "category" text NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "isReminder" boolean NOT NULL,
    "sourceApp" text,
    "processingStatus" text NOT NULL,
    "processingProgress" bigint,
    "processedAt" timestamp without time zone,
    "errorMessage" text
);

-- Indexes
CREATE INDEX "capture_user_idx" ON "capture" USING btree ("userId");
CREATE INDEX "capture_created_idx" ON "capture" USING btree ("createdAt");
CREATE INDEX "capture_category_idx" ON "capture" USING btree ("category");
CREATE INDEX "capture_status_idx" ON "capture" USING btree ("processingStatus");

--
-- Class CaptureCollection as table capture_collection
--
CREATE TABLE "capture_collection" (
    "id" bigserial PRIMARY KEY,
    "captureId" bigint NOT NULL,
    "collectionId" bigint NOT NULL,
    "addedAt" timestamp without time zone NOT NULL
);

-- Indexes
CREATE INDEX "capture_collection_capture_idx" ON "capture_collection" USING btree ("captureId");
CREATE INDEX "capture_collection_collection_idx" ON "capture_collection" USING btree ("collectionId");
CREATE UNIQUE INDEX "capture_collection_unique" ON "capture_collection" USING btree ("captureId", "collectionId");

--
-- Class Collection as table collection
--
CREATE TABLE "collection" (
    "id" bigserial PRIMARY KEY,
    "userId" bigint NOT NULL,
    "name" text NOT NULL,
    "description" text,
    "isAutoGenerated" boolean NOT NULL,
    "coverImageUrl" text,
    "createdAt" timestamp without time zone NOT NULL
);

-- Indexes
CREATE INDEX "collection_user_idx" ON "collection" USING btree ("userId");

--
-- Class Reminder as table reminder
--
CREATE TABLE "reminder" (
    "id" bigserial PRIMARY KEY,
    "userId" bigint NOT NULL,
    "captureId" bigint NOT NULL,
    "message" text,
    "triggerAt" timestamp without time zone NOT NULL,
    "isSent" boolean NOT NULL,
    "isDismissed" boolean NOT NULL,
    "createdAt" timestamp without time zone NOT NULL
);

-- Indexes
CREATE INDEX "reminder_user_idx" ON "reminder" USING btree ("userId");
CREATE INDEX "reminder_capture_idx" ON "reminder" USING btree ("captureId");
CREATE INDEX "reminder_trigger_idx" ON "reminder" USING btree ("triggerAt");

--
-- Class SearchQuery as table search_query
--
CREATE TABLE "search_query" (
    "id" bigserial PRIMARY KEY,
    "userId" bigint NOT NULL,
    "query" text NOT NULL,
    "resultsCount" bigint NOT NULL,
    "clickedCaptureId" bigint,
    "searchedAt" timestamp without time zone NOT NULL
);

-- Indexes
CREATE INDEX "search_query_user_idx" ON "search_query" USING btree ("userId");
CREATE INDEX "search_query_date_idx" ON "search_query" USING btree ("searchedAt");

--
-- Class TokenUsageHistory as table token_usage_history
--
CREATE TABLE "token_usage_history" (
    "id" bigserial PRIMARY KEY,
    "contentType" text NOT NULL,
    "complexityBucket" text NOT NULL,
    "complexityScore" double precision,
    "tokensAllocated" bigint NOT NULL,
    "tokensUsed" bigint NOT NULL,
    "wasComplete" boolean NOT NULL,
    "isQuickAnalysis" boolean NOT NULL,
    "createdAt" timestamp without time zone NOT NULL
);

-- Indexes
CREATE INDEX "token_history_type_idx" ON "token_usage_history" USING btree ("contentType", "complexityBucket");
CREATE INDEX "token_history_created_idx" ON "token_usage_history" USING btree ("createdAt");
CREATE INDEX "token_history_quick_idx" ON "token_usage_history" USING btree ("isQuickAnalysis");

--
-- Class UserPreference as table user_preference
--
CREATE TABLE "user_preference" (
    "id" bigserial PRIMARY KEY,
    "userId" bigint NOT NULL,
    "timezone" text NOT NULL,
    "notificationTime" text,
    "overlayEnabled" boolean NOT NULL,
    "weeklyDigestEnabled" boolean NOT NULL,
    "proactiveRemindersEnabled" boolean NOT NULL,
    "theme" text NOT NULL
);

-- Indexes
CREATE UNIQUE INDEX "user_preference_user_idx" ON "user_preference" USING btree ("userId");

--
-- Class CloudStorageEntry as table serverpod_cloud_storage
--
CREATE TABLE "serverpod_cloud_storage" (
    "id" bigserial PRIMARY KEY,
    "storageId" text NOT NULL,
    "path" text NOT NULL,
    "addedTime" timestamp without time zone NOT NULL,
    "expiration" timestamp without time zone,
    "byteData" bytea NOT NULL,
    "verified" boolean NOT NULL
);

-- Indexes
CREATE UNIQUE INDEX "serverpod_cloud_storage_path_idx" ON "serverpod_cloud_storage" USING btree ("storageId", "path");
CREATE INDEX "serverpod_cloud_storage_expiration" ON "serverpod_cloud_storage" USING btree ("expiration");

--
-- Class CloudStorageDirectUploadEntry as table serverpod_cloud_storage_direct_upload
--
CREATE TABLE "serverpod_cloud_storage_direct_upload" (
    "id" bigserial PRIMARY KEY,
    "storageId" text NOT NULL,
    "path" text NOT NULL,
    "expiration" timestamp without time zone NOT NULL,
    "authKey" text NOT NULL
);

-- Indexes
CREATE UNIQUE INDEX "serverpod_cloud_storage_direct_upload_storage_path" ON "serverpod_cloud_storage_direct_upload" USING btree ("storageId", "path");

--
-- Class FutureCallEntry as table serverpod_future_call
--
CREATE TABLE "serverpod_future_call" (
    "id" bigserial PRIMARY KEY,
    "name" text NOT NULL,
    "time" timestamp without time zone NOT NULL,
    "serializedObject" text,
    "serverId" text NOT NULL,
    "identifier" text
);

-- Indexes
CREATE INDEX "serverpod_future_call_time_idx" ON "serverpod_future_call" USING btree ("time");
CREATE INDEX "serverpod_future_call_serverId_idx" ON "serverpod_future_call" USING btree ("serverId");
CREATE INDEX "serverpod_future_call_identifier_idx" ON "serverpod_future_call" USING btree ("identifier");

--
-- Class ServerHealthConnectionInfo as table serverpod_health_connection_info
--
CREATE TABLE "serverpod_health_connection_info" (
    "id" bigserial PRIMARY KEY,
    "serverId" text NOT NULL,
    "timestamp" timestamp without time zone NOT NULL,
    "active" bigint NOT NULL,
    "closing" bigint NOT NULL,
    "idle" bigint NOT NULL,
    "granularity" bigint NOT NULL
);

-- Indexes
CREATE UNIQUE INDEX "serverpod_health_connection_info_timestamp_idx" ON "serverpod_health_connection_info" USING btree ("timestamp", "serverId", "granularity");

--
-- Class ServerHealthMetric as table serverpod_health_metric
--
CREATE TABLE "serverpod_health_metric" (
    "id" bigserial PRIMARY KEY,
    "name" text NOT NULL,
    "serverId" text NOT NULL,
    "timestamp" timestamp without time zone NOT NULL,
    "isHealthy" boolean NOT NULL,
    "value" double precision NOT NULL,
    "granularity" bigint NOT NULL
);

-- Indexes
CREATE UNIQUE INDEX "serverpod_health_metric_timestamp_idx" ON "serverpod_health_metric" USING btree ("timestamp", "serverId", "name", "granularity");

--
-- Class LogEntry as table serverpod_log
--
CREATE TABLE "serverpod_log" (
    "id" bigserial PRIMARY KEY,
    "sessionLogId" bigint NOT NULL,
    "messageId" bigint,
    "reference" text,
    "serverId" text NOT NULL,
    "time" timestamp without time zone NOT NULL,
    "logLevel" bigint NOT NULL,
    "message" text NOT NULL,
    "error" text,
    "stackTrace" text,
    "order" bigint NOT NULL
);

-- Indexes
CREATE INDEX "serverpod_log_sessionLogId_idx" ON "serverpod_log" USING btree ("sessionLogId");

--
-- Class MessageLogEntry as table serverpod_message_log
--
CREATE TABLE "serverpod_message_log" (
    "id" bigserial PRIMARY KEY,
    "sessionLogId" bigint NOT NULL,
    "serverId" text NOT NULL,
    "messageId" bigint NOT NULL,
    "endpoint" text NOT NULL,
    "messageName" text NOT NULL,
    "duration" double precision NOT NULL,
    "error" text,
    "stackTrace" text,
    "slow" boolean NOT NULL,
    "order" bigint NOT NULL
);

--
-- Class MethodInfo as table serverpod_method
--
CREATE TABLE "serverpod_method" (
    "id" bigserial PRIMARY KEY,
    "endpoint" text NOT NULL,
    "method" text NOT NULL
);

-- Indexes
CREATE UNIQUE INDEX "serverpod_method_endpoint_method_idx" ON "serverpod_method" USING btree ("endpoint", "method");

--
-- Class DatabaseMigrationVersion as table serverpod_migrations
--
CREATE TABLE "serverpod_migrations" (
    "id" bigserial PRIMARY KEY,
    "module" text NOT NULL,
    "version" text NOT NULL,
    "timestamp" timestamp without time zone
);

-- Indexes
CREATE UNIQUE INDEX "serverpod_migrations_ids" ON "serverpod_migrations" USING btree ("module");

--
-- Class QueryLogEntry as table serverpod_query_log
--
CREATE TABLE "serverpod_query_log" (
    "id" bigserial PRIMARY KEY,
    "serverId" text NOT NULL,
    "sessionLogId" bigint NOT NULL,
    "messageId" bigint,
    "query" text NOT NULL,
    "duration" double precision NOT NULL,
    "numRows" bigint,
    "error" text,
    "stackTrace" text,
    "slow" boolean NOT NULL,
    "order" bigint NOT NULL
);

-- Indexes
CREATE INDEX "serverpod_query_log_sessionLogId_idx" ON "serverpod_query_log" USING btree ("sessionLogId");

--
-- Class ReadWriteTestEntry as table serverpod_readwrite_test
--
CREATE TABLE "serverpod_readwrite_test" (
    "id" bigserial PRIMARY KEY,
    "number" bigint NOT NULL
);

--
-- Class RuntimeSettings as table serverpod_runtime_settings
--
CREATE TABLE "serverpod_runtime_settings" (
    "id" bigserial PRIMARY KEY,
    "logSettings" json NOT NULL,
    "logSettingsOverrides" json NOT NULL,
    "logServiceCalls" boolean NOT NULL,
    "logMalformedCalls" boolean NOT NULL
);

--
-- Class SessionLogEntry as table serverpod_session_log
--
CREATE TABLE "serverpod_session_log" (
    "id" bigserial PRIMARY KEY,
    "serverId" text NOT NULL,
    "time" timestamp without time zone NOT NULL,
    "module" text,
    "endpoint" text,
    "method" text,
    "duration" double precision,
    "numQueries" bigint,
    "slow" boolean,
    "error" text,
    "stackTrace" text,
    "authenticatedUserId" bigint,
    "isOpen" boolean,
    "touched" timestamp without time zone NOT NULL
);

-- Indexes
CREATE INDEX "serverpod_session_log_serverid_idx" ON "serverpod_session_log" USING btree ("serverId");
CREATE INDEX "serverpod_session_log_touched_idx" ON "serverpod_session_log" USING btree ("touched");
CREATE INDEX "serverpod_session_log_isopen_idx" ON "serverpod_session_log" USING btree ("isOpen");

--
-- Foreign relations for "serverpod_log" table
--
ALTER TABLE ONLY "serverpod_log"
    ADD CONSTRAINT "serverpod_log_fk_0"
    FOREIGN KEY("sessionLogId")
    REFERENCES "serverpod_session_log"("id")
    ON DELETE CASCADE
    ON UPDATE NO ACTION;

--
-- Foreign relations for "serverpod_message_log" table
--
ALTER TABLE ONLY "serverpod_message_log"
    ADD CONSTRAINT "serverpod_message_log_fk_0"
    FOREIGN KEY("sessionLogId")
    REFERENCES "serverpod_session_log"("id")
    ON DELETE CASCADE
    ON UPDATE NO ACTION;

--
-- Foreign relations for "serverpod_query_log" table
--
ALTER TABLE ONLY "serverpod_query_log"
    ADD CONSTRAINT "serverpod_query_log_fk_0"
    FOREIGN KEY("sessionLogId")
    REFERENCES "serverpod_session_log"("id")
    ON DELETE CASCADE
    ON UPDATE NO ACTION;


--
-- MIGRATION VERSION FOR recall_butler
--
INSERT INTO "serverpod_migrations" ("module", "version", "timestamp")
    VALUES ('recall_butler', '20251218095609214', now())
    ON CONFLICT ("module")
    DO UPDATE SET "version" = '20251218095609214', "timestamp" = now();

--
-- MIGRATION VERSION FOR serverpod
--
INSERT INTO "serverpod_migrations" ("module", "version", "timestamp")
    VALUES ('serverpod', '20240516151843329', now())
    ON CONFLICT ("module")
    DO UPDATE SET "version" = '20240516151843329', "timestamp" = now();


COMMIT;
