/* AUTOMATICALLY GENERATED CODE DO NOT MODIFY */
/*   To generate run: "serverpod generate"    */

// ignore_for_file: implementation_imports
// ignore_for_file: library_private_types_in_public_api
// ignore_for_file: non_constant_identifier_names
// ignore_for_file: public_member_api_docs
// ignore_for_file: type_literal_in_constant_pattern
// ignore_for_file: use_super_parameters

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:serverpod_client/serverpod_client.dart' as _i1;

/// Collection model - groups of related captures
abstract class Collection implements _i1.SerializableModel {
  Collection._({
    this.id,
    required this.userId,
    required this.name,
    this.description,
    required this.isAutoGenerated,
    this.coverImageUrl,
    required this.createdAt,
  });

  factory Collection({
    int? id,
    required int userId,
    required String name,
    String? description,
    required bool isAutoGenerated,
    String? coverImageUrl,
    required DateTime createdAt,
  }) = _CollectionImpl;

  factory Collection.fromJson(Map<String, dynamic> jsonSerialization) {
    return Collection(
      id: jsonSerialization['id'] as int?,
      userId: jsonSerialization['userId'] as int,
      name: jsonSerialization['name'] as String,
      description: jsonSerialization['description'] as String?,
      isAutoGenerated: jsonSerialization['isAutoGenerated'] as bool,
      coverImageUrl: jsonSerialization['coverImageUrl'] as String?,
      createdAt:
          _i1.DateTimeJsonExtension.fromJson(jsonSerialization['createdAt']),
    );
  }

  /// The database id, set if the object has been inserted into the
  /// database or if it has been fetched from the database. Otherwise,
  /// the id will be null.
  int? id;

  /// Foreign key to user
  int userId;

  /// Collection name
  String name;

  /// Optional description
  String? description;

  /// Whether this collection was auto-generated by AI
  bool isAutoGenerated;

  /// Representative image URL for the collection
  String? coverImageUrl;

  /// Creation timestamp
  DateTime createdAt;

  /// Returns a shallow copy of this [Collection]
  /// with some or all fields replaced by the given arguments.
  @_i1.useResult
  Collection copyWith({
    int? id,
    int? userId,
    String? name,
    String? description,
    bool? isAutoGenerated,
    String? coverImageUrl,
    DateTime? createdAt,
  });
  @override
  Map<String, dynamic> toJson() {
    return {
      if (id != null) 'id': id,
      'userId': userId,
      'name': name,
      if (description != null) 'description': description,
      'isAutoGenerated': isAutoGenerated,
      if (coverImageUrl != null) 'coverImageUrl': coverImageUrl,
      'createdAt': createdAt.toJson(),
    };
  }

  @override
  String toString() {
    return _i1.SerializationManager.encode(this);
  }
}

class _Undefined {}

class _CollectionImpl extends Collection {
  _CollectionImpl({
    int? id,
    required int userId,
    required String name,
    String? description,
    required bool isAutoGenerated,
    String? coverImageUrl,
    required DateTime createdAt,
  }) : super._(
          id: id,
          userId: userId,
          name: name,
          description: description,
          isAutoGenerated: isAutoGenerated,
          coverImageUrl: coverImageUrl,
          createdAt: createdAt,
        );

  /// Returns a shallow copy of this [Collection]
  /// with some or all fields replaced by the given arguments.
  @_i1.useResult
  @override
  Collection copyWith({
    Object? id = _Undefined,
    int? userId,
    String? name,
    Object? description = _Undefined,
    bool? isAutoGenerated,
    Object? coverImageUrl = _Undefined,
    DateTime? createdAt,
  }) {
    return Collection(
      id: id is int? ? id : this.id,
      userId: userId ?? this.userId,
      name: name ?? this.name,
      description: description is String? ? description : this.description,
      isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
      coverImageUrl:
          coverImageUrl is String? ? coverImageUrl : this.coverImageUrl,
      createdAt: createdAt ?? this.createdAt,
    );
  }
}
