BEGIN;

--
-- ACTION CREATE TABLE
--
CREATE TABLE "capture" (
    "id" bigserial PRIMARY KEY,
    "userId" bigint NOT NULL,
    "type" text NOT NULL,
    "originalUrl" text,
    "thumbnailUrl" text,
    "extractedText" text,
    "aiSummary" text,
    "tags" text,
    "category" text NOT NULL,
    "createdAt" timestamp without time zone NOT NULL,
    "isReminder" boolean NOT NULL,
    "sourceApp" text,
    "processingStatus" text NOT NULL
);

-- Indexes
CREATE INDEX "capture_user_idx" ON "capture" USING btree ("userId");
CREATE INDEX "capture_created_idx" ON "capture" USING btree ("createdAt");
CREATE INDEX "capture_category_idx" ON "capture" USING btree ("category");

--
-- ACTION CREATE TABLE
--
CREATE TABLE "capture_collection" (
    "id" bigserial PRIMARY KEY,
    "captureId" bigint NOT NULL,
    "collectionId" bigint NOT NULL,
    "addedAt" timestamp without time zone NOT NULL
);

-- Indexes
CREATE INDEX "capture_collection_capture_idx" ON "capture_collection" USING btree ("captureId");
CREATE INDEX "capture_collection_collection_idx" ON "capture_collection" USING btree ("collectionId");
CREATE UNIQUE INDEX "capture_collection_unique" ON "capture_collection" USING btree ("captureId", "collectionId");

--
-- ACTION CREATE TABLE
--
CREATE TABLE "collection" (
    "id" bigserial PRIMARY KEY,
    "userId" bigint NOT NULL,
    "name" text NOT NULL,
    "description" text,
    "isAutoGenerated" boolean NOT NULL,
    "coverImageUrl" text,
    "createdAt" timestamp without time zone NOT NULL
);

-- Indexes
CREATE INDEX "collection_user_idx" ON "collection" USING btree ("userId");

--
-- ACTION CREATE TABLE
--
CREATE TABLE "reminder" (
    "id" bigserial PRIMARY KEY,
    "userId" bigint NOT NULL,
    "captureId" bigint NOT NULL,
    "message" text,
    "triggerAt" timestamp without time zone NOT NULL,
    "isSent" boolean NOT NULL,
    "isDismissed" boolean NOT NULL,
    "createdAt" timestamp without time zone NOT NULL
);

-- Indexes
CREATE INDEX "reminder_user_idx" ON "reminder" USING btree ("userId");
CREATE INDEX "reminder_capture_idx" ON "reminder" USING btree ("captureId");
CREATE INDEX "reminder_trigger_idx" ON "reminder" USING btree ("triggerAt");

--
-- ACTION CREATE TABLE
--
CREATE TABLE "search_query" (
    "id" bigserial PRIMARY KEY,
    "userId" bigint NOT NULL,
    "query" text NOT NULL,
    "resultsCount" bigint NOT NULL,
    "clickedCaptureId" bigint,
    "searchedAt" timestamp without time zone NOT NULL
);

-- Indexes
CREATE INDEX "search_query_user_idx" ON "search_query" USING btree ("userId");
CREATE INDEX "search_query_date_idx" ON "search_query" USING btree ("searchedAt");

--
-- ACTION CREATE TABLE
--
CREATE TABLE "user_preference" (
    "id" bigserial PRIMARY KEY,
    "userId" bigint NOT NULL,
    "timezone" text NOT NULL,
    "notificationTime" text,
    "overlayEnabled" boolean NOT NULL,
    "weeklyDigestEnabled" boolean NOT NULL,
    "proactiveRemindersEnabled" boolean NOT NULL,
    "theme" text NOT NULL
);

-- Indexes
CREATE UNIQUE INDEX "user_preference_user_idx" ON "user_preference" USING btree ("userId");


--
-- MIGRATION VERSION FOR recall_butler
--
INSERT INTO "serverpod_migrations" ("module", "version", "timestamp")
    VALUES ('recall_butler', '20251216112545421', now())
    ON CONFLICT ("module")
    DO UPDATE SET "version" = '20251216112545421', "timestamp" = now();

--
-- MIGRATION VERSION FOR serverpod
--
INSERT INTO "serverpod_migrations" ("module", "version", "timestamp")
    VALUES ('serverpod', '20240516151843329', now())
    ON CONFLICT ("module")
    DO UPDATE SET "version" = '20240516151843329', "timestamp" = now();


COMMIT;
